install_data(
  'io.github.the0megastar.Glyph.desktop',
  install_dir: get_option('datadir') / 'applications',
)

install_data(
  'icons/io.github.the0megastar.Glyph.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'apps',
)

install_data(
  'io.github.the0megastar.Glyph.metainfo.xml',
  install_dir: get_option('datadir') / 'metainfo',
)
